/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vote;

import java.awt.*;

/**
 *
 * @author SRIKANTA JENA
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
         initComponents();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-890)/2, (screenSize.height-540)/2, 890, 540);
        
        
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     
  
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        vtreg = new javax.swing.JButton();
        label2 = new java.awt.Label();
        vst = new javax.swing.JButton();
        label5 = new java.awt.Label();
        vtset = new javax.swing.JButton();
        label4 = new java.awt.Label();
        creg = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        i = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        back = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        label3 = new java.awt.Label();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(890, 540));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setBackground(new java.awt.Color(153, 255, 153));
        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("VOTER  REGISTRATION");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        vtreg.setBackground(new java.awt.Color(0, 204, 204));
        vtreg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vtreg.setForeground(new java.awt.Color(0, 153, 153));
        vtreg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vote/REGHOME.png"))); // NOI18N
        vtreg.setBorder(null);
        vtreg.setContentAreaFilled(false);
        vtreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vtregMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vtregMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vtregMouseExited(evt);
            }
        });
        vtreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtregActionPerformed(evt);
            }
        });
        jPanel1.add(vtreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 130, 140));

        label2.setBackground(new java.awt.Color(153, 255, 153));
        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("START VOTING");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, -1, -1));

        vst.setBackground(new java.awt.Color(0, 204, 204));
        vst.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vst.setForeground(new java.awt.Color(0, 153, 153));
        vst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vote/STARTVOTE.png"))); // NOI18N
        vst.setBorder(null);
        vst.setContentAreaFilled(false);
        vst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vstMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vstMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vstMouseExited(evt);
            }
        });
        vst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vstActionPerformed(evt);
            }
        });
        jPanel1.add(vst, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 100, 140));

        label5.setBackground(new java.awt.Color(153, 255, 153));
        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("VOTEING PREFERENCE");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, -1, -1));

        vtset.setBackground(new java.awt.Color(0, 204, 204));
        vtset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vtset.setForeground(new java.awt.Color(0, 153, 153));
        vtset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vote/MACHINE.png"))); // NOI18N
        vtset.setBorder(null);
        vtset.setContentAreaFilled(false);
        vtset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vtsetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vtsetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vtsetMouseExited(evt);
            }
        });
        vtset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtsetActionPerformed(evt);
            }
        });
        jPanel1.add(vtset, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, 140));

        label4.setBackground(new java.awt.Color(153, 255, 153));
        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("CANDIDATE REGISTRATION");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 160, -1));

        creg.setBackground(new java.awt.Color(0, 204, 204));
        creg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        creg.setForeground(new java.awt.Color(0, 153, 153));
        creg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vote/REGHOME copy.png"))); // NOI18N
        creg.setBorder(null);
        creg.setContentAreaFilled(false);
        creg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cregMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cregMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cregMouseExited(evt);
            }
        });
        creg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cregActionPerformed(evt);
            }
        });
        jPanel1.add(creg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 170, 140));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 10, 190));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vote/flag.gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 140, 90));

        jLabel1.setBackground(new java.awt.Color(102, 255, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vote/ADBG.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 890, 330));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("INSTRUCTION:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 20));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setText("VOTER");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 118, 30));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setText("ELECTION");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 100, 30));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 204));
        jLabel14.setText("A LITTLE BIT OF INSTRUCTION ABOUT ADMIN CONTROL WILL BE WRITTEN");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 510, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vote/logomini.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, -1, 39));

        jButton5.setBackground(new java.awt.Color(0, 204, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 153, 153));
        jButton5.setText("BACK");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 110, 30));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        i.setBackground(new java.awt.Color(0, 204, 204));
        i.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        i.setForeground(new java.awt.Color(0, 153, 153));
        i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vote/ABOUT1.png"))); // NOI18N
        i.setBorder(null);
        i.setContentAreaFilled(false);
        i.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iMouseExited(evt);
            }
        });
        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });

        refresh.setBackground(new java.awt.Color(0, 204, 204));
        refresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        refresh.setForeground(new java.awt.Color(0, 153, 153));
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vote/REFRESH.png"))); // NOI18N
        refresh.setBorder(null);
        refresh.setContentAreaFilled(false);
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshMouseExited(evt);
            }
        });
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 204, 204));
        back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(0, 153, 153));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vote/BACK.png"))); // NOI18N
        back.setBorder(null);
        back.setContentAreaFilled(false);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(0, 204, 204));
        exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 153, 153));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vote/EXIT.png"))); // NOI18N
        exit.setBorder(null);
        exit.setContentAreaFilled(false);
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("DotumChe", 0, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(204, 204, 0));
        label3.setText("ADMIN CONTROL PANEL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 506, Short.MAX_VALUE)
                .addComponent(i)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(i, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 50));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 204, 204));
        jLabel17.setText("A LITTLE BIT OF INSTRUCTION ABOUT ADMIN CONTROL WILL BE WRITTEN");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 510, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        
        loginAdmin lad=new loginAdmin();
        lad.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered

         exit.setSize(38,33);
    }//GEN-LAST:event_exitMouseEntered

    private void vtsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtsetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vtsetActionPerformed

    private void vtregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtregActionPerformed
        // TODO add your handling code here:
        Vreg vr = new  Vreg();
        vr.setVisible(true);
        dispose();
    }//GEN-LAST:event_vtregActionPerformed

    private void cregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cregActionPerformed

    private void cregMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cregMouseExited
        // TODO add your handling code here:
        creg.setSize(161, 131);
    }//GEN-LAST:event_cregMouseExited

    private void cregMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cregMouseEntered
        // TODO add your handling code here:
 audioclass ac = new audioclass();
ac.c_reg.play();
        int a;
        for (a = 161; a <= 200; a++) {
            creg.setSize(a, 131);
        }


    }//GEN-LAST:event_cregMouseEntered

    private void vstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vstActionPerformed
        // TODO add your handling code here:
        vstarted vs= new vstarted();
        vs.setVisible(true);
        dispose();
    }//GEN-LAST:event_vstActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        loginAdmin la = new loginAdmin();
        la.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void vtregMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vtregMouseEntered
        // TODO add your handling code here:
        
         audioclass ac = new audioclass();
ac.vreg.play();
        int a;
        for (a = 141; a <= 200; a++) {
            vtreg.setSize(a, 135);
        }
    }//GEN-LAST:event_vtregMouseEntered

    private void vtregMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vtregMouseExited
        // TODO add your handling code here:
        vtreg.setSize(141, 135);
    }//GEN-LAST:event_vtregMouseExited

    private void vtsetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vtsetMouseEntered
        // TODO add your handling code here:
         audioclass ac = new audioclass();
ac.vpref.play();
             vtset.setSize(200, 135);
    }//GEN-LAST:event_vtsetMouseEntered

    private void vtsetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vtsetMouseExited
        // TODO add your handling code here:
              vtset.setSize(141, 135);
    }//GEN-LAST:event_vtsetMouseExited

    private void vstMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vstMouseEntered
        // TODO add your handling code here:
         audioclass ac = new audioclass();
ac.stvt.play();
              vst.setSize(180,127);
    }//GEN-LAST:event_vstMouseEntered

    private void vstMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vstMouseExited
        // TODO add your handling code here:
              vst.setSize(121, 127);
    }//GEN-LAST:event_vstMouseExited

    private void cregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cregMouseClicked
        // TODO add your handling code here:
        Cdialog cd = new Cdialog();
        cd.setVisible(true);
    }//GEN-LAST:event_cregMouseClicked

    private void vtregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vtregMouseClicked
        // TODO add your handling code here:
           Cdialog cd = new Cdialog();
        cd.setVisible(true);
    }//GEN-LAST:event_vtregMouseClicked

    private void vtsetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vtsetMouseClicked
        // TODO add your handling code here:
           Cdialog cd = new Cdialog();
        cd.setVisible(true);
    }//GEN-LAST:event_vtsetMouseClicked

    private void vstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vstMouseClicked
        // TODO add your handling code here:
           Cdialog cd = new Cdialog();
        cd.setVisible(true);
    }//GEN-LAST:event_vstMouseClicked

    private void iMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iMouseEntered
        // TODO add your handling code here:
        i.setSize(38,33);
    }//GEN-LAST:event_iMouseEntered

    private void iMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iMouseExited
        // TODO add your handling code here:
        i.setSize(30,33);
    }//GEN-LAST:event_iMouseExited

    private void refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseEntered
       // TODO add your handling code here:
        refresh.setSize(38,33);
    }//GEN-LAST:event_refreshMouseEntered

    private void refreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseExited
        // TODO add your handling code here:
         refresh.setSize(30,33);
    }//GEN-LAST:event_refreshMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
         back.setSize(38,33);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
         back.setSize(30,33);
    }//GEN-LAST:event_backMouseExited

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        // TODO add your handling code here:
         exit.setSize(30,33);
    }//GEN-LAST:event_exitMouseExited

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new admin().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton creg;
    private javax.swing.JButton exit;
    private javax.swing.JButton i;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JButton refresh;
    private javax.swing.JButton vst;
    private javax.swing.JButton vtreg;
    private javax.swing.JButton vtset;
    // End of variables declaration//GEN-END:variables
}
