/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vote;

import com.github.sarxos.webcam.Webcam;
import java.awt.AWTException;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;

/**
 *
 * @author SRIKANTA JENA
 */
public class Vreg extends javax.swing.JFrame {

    /**
     * Creates new form Vreg
     */
    public Vreg() {
        initComponents();
                     java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-890)/2, (screenSize.height-540)/2, 890, 540);
        printpaper.setVisible(false);
 
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        i = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        back = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        label3 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        vname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        vmail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        vcon = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        vaadhaar = new javax.swing.JTextField();
        vpass = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        takepic = new javax.swing.JButton();
        back5 = new javax.swing.JButton();
        printpaper = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pname = new javax.swing.JLabel();
        pid = new javax.swing.JLabel();
        pcon = new javax.swing.JLabel();
        paadhaar = new javax.swing.JLabel();
        pmail = new javax.swing.JLabel();
        cpic_p = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        pqr = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        canphoto = new javax.swing.JLabel();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        i.setBackground(new java.awt.Color(0, 204, 204));
        i.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        i.setForeground(new java.awt.Color(0, 153, 153));
        i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vote/ABOUT1.png"))); // NOI18N
        i.setBorder(null);
        i.setContentAreaFilled(false);
        i.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iMouseExited(evt);
            }
        });
        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });
        jPanel3.add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 11, -1, 39));

        refresh.setBackground(new java.awt.Color(0, 204, 204));
        refresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        refresh.setForeground(new java.awt.Color(0, 153, 153));
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vote/REFRESH.png"))); // NOI18N
        refresh.setBorder(null);
        refresh.setContentAreaFilled(false);
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshMouseExited(evt);
            }
        });
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel3.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 11, -1, 39));

        back.setBackground(new java.awt.Color(0, 204, 204));
        back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(0, 153, 153));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vote/BACK.png"))); // NOI18N
        back.setBorder(null);
        back.setContentAreaFilled(false);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel3.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 11, -1, 39));

        exit.setBackground(new java.awt.Color(0, 204, 204));
        exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 153, 153));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vote/EXIT.png"))); // NOI18N
        exit.setBorder(null);
        exit.setContentAreaFilled(false);
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel3.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(849, 11, -1, 39));

        label3.setFont(new java.awt.Font("DotumChe", 0, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(204, 204, 0));
        label3.setText("VOTER REGESTRATION FORM");
        jPanel3.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 222, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 50));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setText("VOTER REGESTRATION");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("NAME");

        vname.setBackground(new java.awt.Color(0, 102, 102));
        vname.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        vname.setForeground(new java.awt.Color(204, 204, 0));
        vname.setName("adminid");
        vname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnameActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("E-MAIL");

        vmail.setBackground(new java.awt.Color(0, 102, 102));
        vmail.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        vmail.setForeground(new java.awt.Color(204, 204, 0));
        vmail.setName("adminid");
        vmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vmailActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CONTACT");

        vcon.setBackground(new java.awt.Color(0, 102, 102));
        vcon.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        vcon.setForeground(new java.awt.Color(204, 204, 0));
        vcon.setName("adminid");
        vcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vconActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("AADHAAR NO");

        vaadhaar.setBackground(new java.awt.Color(0, 102, 102));
        vaadhaar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        vaadhaar.setForeground(new java.awt.Color(204, 204, 0));
        vaadhaar.setName("adminid");
        vaadhaar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaadhaarActionPerformed(evt);
            }
        });

        vpass.setBackground(new java.awt.Color(0, 102, 102));
        vpass.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        vpass.setForeground(new java.awt.Color(204, 204, 0));
        vpass.setName("adminid");
        vpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vpassActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("4 DIGIT PASSWORD");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("CANDIDATE PHOTO");

        takepic.setBackground(new java.awt.Color(0, 204, 204));
        takepic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        takepic.setForeground(new java.awt.Color(153, 255, 102));
        takepic.setText("TAKE PICTURE");
        takepic.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        takepic.setContentAreaFilled(false);
        takepic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                takepicMouseEntered(evt);
            }
        });
        takepic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takepicActionPerformed(evt);
            }
        });

        back5.setBackground(new java.awt.Color(0, 204, 204));
        back5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        back5.setForeground(new java.awt.Color(51, 204, 255));
        back5.setText("GENERATE TOKEN");
        back5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        back5.setContentAreaFilled(false);
        back5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back5MouseClicked(evt);
            }
        });
        back5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back5ActionPerformed(evt);
            }
        });

        printpaper.setBackground(new java.awt.Color(204, 255, 204));
        printpaper.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vote/logomini.png"))); // NOI18N
        printpaper.add(jLabel3);
        jLabel3.setBounds(10, 0, 100, 60);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("NAME");
        printpaper.add(jLabel20);
        jLabel20.setBounds(170, 70, 88, 16);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("E-MAIL");
        printpaper.add(jLabel21);
        jLabel21.setBounds(170, 160, 88, 15);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("CONTACT");
        printpaper.add(jLabel22);
        jLabel22.setBounds(170, 120, 88, 15);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("AADHAAR NO");
        printpaper.add(jLabel23);
        jLabel23.setBounds(170, 140, 88, 15);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("VOTER ID");
        printpaper.add(jLabel24);
        jLabel24.setBounds(170, 90, 88, 15);

        pname.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        pname.setText("NAME");
        printpaper.add(pname);
        pname.setBounds(270, 70, 197, 16);

        pid.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        pid.setText("VOTER ID");
        printpaper.add(pid);
        pid.setBounds(270, 90, 197, 15);

        pcon.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        pcon.setText("CONTACT");
        printpaper.add(pcon);
        pcon.setBounds(270, 120, 197, 13);

        paadhaar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        paadhaar.setText("AADHAAR NO");
        printpaper.add(paadhaar);
        paadhaar.setBounds(270, 140, 197, 13);

        pmail.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        pmail.setText("E-MAIL");
        printpaper.add(pmail);
        pmail.setBounds(270, 160, 197, 13);

        cpic_p.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        printpaper.add(cpic_p);
        cpic_p.setBounds(27, 71, 120, 101);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("VOTING TITLE");
        printpaper.add(jLabel30);
        jLabel30.setBounds(141, 11, 366, 15);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel31.setText("VOTING SUBTITLE");
        printpaper.add(jLabel31);
        jLabel31.setBounds(141, 32, 366, 13);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setText("THIS IS A COMPUTER GENERATED QR CODE");
        printpaper.add(jLabel32);
        jLabel32.setBounds(167, 196, 321, 10);

        pqr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        printpaper.add(pqr);
        pqr.setBounds(20, 190, 130, 100);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("FOR PASSWORD AUTHENTICATION.");
        printpaper.add(jLabel33);
        jLabel33.setBounds(167, 212, 321, 15);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setText("THIS IS A COMPUTER GENERATED QR CODE");
        printpaper.add(jLabel34);
        jLabel34.setBounds(167, 238, 321, 15);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setText("FOR PASSWORD AUTHENTICATION.");
        printpaper.add(jLabel35);
        jLabel35.setBounds(167, 259, 321, 10);

        canphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        print.setBackground(new java.awt.Color(0, 204, 204));
        print.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        print.setForeground(new java.awt.Color(51, 204, 255));
        print.setText("PRINT");
        print.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        print.setContentAreaFilled(false);
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(canphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(takepic, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel18))))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vpass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vname, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vaadhaar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(back5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 243, Short.MAX_VALUE))
                    .addComponent(printpaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vcon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vaadhaar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vpass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 49, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(canphoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(takepic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(printpaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 890, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iMouseEntered
        // TODO add your handling code here:
        i.setSize(38, 33);
    }//GEN-LAST:event_iMouseEntered

    private void iMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iMouseExited
        // TODO add your handling code here:
        i.setSize(30, 33);
    }//GEN-LAST:event_iMouseExited

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iActionPerformed

    private void refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseEntered
        // TODO add your handling code here:
        refresh.setSize(38, 33);
    }//GEN-LAST:event_refreshMouseEntered

    private void refreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseExited
        // TODO add your handling code here:
        refresh.setSize(30, 33);
    }//GEN-LAST:event_refreshMouseExited

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        Vreg vrg = new Vreg();
        vrg.setVisible(true);
        dispose();
    }//GEN-LAST:event_refreshActionPerformed

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        back.setSize(38, 33);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        back.setSize(30, 33);
    }//GEN-LAST:event_backMouseExited

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        admin ad = new admin();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered

        exit.setSize(38, 33);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        // TODO add your handling code here:
        exit.setSize(30, 33);
    }//GEN-LAST:event_exitMouseExited

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void vnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vnameActionPerformed

    private void vmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vmailActionPerformed

    private void vconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vconActionPerformed

    private void vaadhaarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaadhaarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaadhaarActionPerformed

    private void vpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vpassActionPerformed

    private void takepicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takepicActionPerformed
        // TODO add your handling code here:
        audioclass ac = new audioclass();
                          Webcam webcam = Webcam.getDefault();
           
ac.lkcamera.play();
        webcam.open();
        
        ImageIcon icon2 = new ImageIcon(webcam.getImage()); 
        canphoto.setIcon(icon2);
        ac.btncrf.play();
        webcam.close();
        
ac.rtk.play();
    }//GEN-LAST:event_takepicActionPerformed

    private void back5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_back5ActionPerformed

    private void back5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back5MouseClicked
    
            printpaper.setVisible(true);  

                cpic_p.setIcon(canphoto.getIcon());
                pname.setText(vname.getText());
                
                pcon.setText(vcon.getText());
                paadhaar.setText(vaadhaar.getText());
                pmail.setText(vmail.getText());
                pid.setText("SVS."+vmail.getText());
 String QRpass = "SVS20"+pcon.getText()+vpass.getText();     
     
          try
        {
        File file = new File("C:\\SVS1.0\\data\\voter\\qrcode\\"+"SVS20"+pcon.getText()+vpass.getText()+"defQR.jpg");
      
        ByteArrayOutputStream out = QRCode.from(QRpass).to(ImageType.JPG).stream();
            try (FileOutputStream fos = new FileOutputStream(file)) 
            {
                fos.write(out.toByteArray());
            }
      ImageIcon icqr = new ImageIcon("C:\\SVS1.0\\data\\voter\\qrcode\\"+"SVS20"+pcon.getText()+vpass.getText()+"defQR.jpg");
      pqr.setIcon(icqr);
        System.out.println("QR generation completed");
        }
        catch(Exception e){}   
    }//GEN-LAST:event_back5MouseClicked

    private void takepicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_takepicMouseEntered
        // TODO add your handling code here:
        audioclass ac = new audioclass();
ac.scam.play();
    }//GEN-LAST:event_takepicMouseEntered

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        try {
            // TODO add your handling code here:
               Rectangle screenrect2 = new Rectangle(printpaper.getLocationOnScreen().x, printpaper.getLocationOnScreen().y, printpaper.getWidth(), printpaper.getHeight());
            BufferedImage capture2 = new Robot().createScreenCapture(screenrect2);
            try {
                ImageIO.write(capture2,"png", new File("C:\\SVS1.0\\data\\voter\\token\\"+vcon.getText()+"voter"+vname.getText()+"token"+".png"));
                  audioclass ac = new audioclass();
           ac.tkprntd.play();
           
            } catch (IOException ex) {
                Logger.getLogger(Vreg.class.getName()).log(Level.SEVERE, null, ex);
            }
       
        JOptionPane.showMessageDialog(this,"TOKEN SAVED");
        
        } catch (AWTException ex) {
            Logger.getLogger(Vreg.class.getName()).log(Level.SEVERE, null, ex);
          
        }
        
    }//GEN-LAST:event_printMouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Vreg().setVisible(true);
                
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton back5;
    private javax.swing.JLabel canphoto;
    private javax.swing.JLabel cpic_p;
    private javax.swing.JButton exit;
    private javax.swing.JButton i;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label label3;
    private javax.swing.JLabel paadhaar;
    private javax.swing.JLabel pcon;
    private javax.swing.JLabel pid;
    private javax.swing.JLabel pmail;
    private javax.swing.JLabel pname;
    private javax.swing.JLabel pqr;
    private javax.swing.JButton print;
    private javax.swing.JPanel printpaper;
    private javax.swing.JButton refresh;
    private javax.swing.JButton takepic;
    private javax.swing.JTextField vaadhaar;
    private javax.swing.JTextField vcon;
    private javax.swing.JTextField vmail;
    private javax.swing.JTextField vname;
    private javax.swing.JTextField vpass;
    // End of variables declaration//GEN-END:variables
}
